import { Notice, Benefit, Coupon, CoexEvent, CommunityPost, ParkingInfo, ContactDept, Poll } from '../types';

export const mockNotices: Notice[] = [
  {
    id: '1',
    title: '[공사] GITC 공사 관련 이동 동선 안내',
    category: 'construction',
    content: 'GITC 공사로 인해 B1층 통행로가 변경됩니다. 정문 우측 임시 통로를 이용해 주시기 바랍니다.',
    targetBuilding: 'WTC SEOUL',
    startDate: '2026-04-24',
    endDate: '2026-06-30',
    isUrgent: false,
    contactPhone: '02-6000-1234',
    createdAt: '2026-04-24',
  },
  {
    id: '2',
    title: '[운영] 주차장 이용 안내',
    category: 'operations',
    content: '코엑스몰 행사 기간 동안 주차 혼잡이 예상됩니다. 대중교통 이용을 권장합니다.',
    targetBuilding: 'WTC SEOUL',
    startDate: '2026-04-20',
    endDate: '2026-04-30',
    isUrgent: false,
    contactPhone: '02-6000-5678',
    createdAt: '2026-04-20',
  },
  {
    id: '3',
    title: '[긴급] 엘리베이터 A동 3호기 점검 안내',
    category: 'urgent',
    content: 'A동 3호기 엘리베이터가 긴급 점검으로 인해 4시간 운행이 중단됩니다.',
    targetBuilding: 'WTC SEOUL',
    startDate: '2026-04-24',
    endDate: '2026-04-24',
    isUrgent: true,
    contactPhone: '02-6000-9999',
    createdAt: '2026-04-24',
  },
  {
    id: '4',
    title: '[점검] 냉난방 설비 정기점검 안내',
    category: 'construction',
    content: '5월 정기 냉난방 설비 점검이 진행됩니다. 점검 시간 동안 일부 층 냉난방이 중단됩니다.',
    targetBuilding: 'WTC SEOUL',
    startDate: '2026-05-10',
    endDate: '2026-05-10',
    isUrgent: false,
    contactPhone: '02-6000-1111',
    createdAt: '2026-04-22',
  },
];

export const mockBenefits: Benefit[] = [
  {
    id: '1',
    title: '코엑스몰 F&B 10% 할인',
    brandName: '코엑스몰 식당가',
    category: 'fnb',
    description: '입주사 직원 전용 F&B 할인 혜택입니다.',
    discountText: '10% 할인',
    location: '코엑스몰 B1 식당가',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    imageUrl: '',
    isActive: true,
    usageMethod: '앱에서 쿠폰 다운로드 후 매장에서 제시',
    notes: '1일 1회 사용 가능. 타 할인과 중복 불가.',
  },
  {
    id: '2',
    title: '호텔 인터컨티넨탈 레스토랑 입주사 우대',
    brandName: '인터컨티넨탈 서울 코엑스',
    category: 'hotel',
    description: '입주사 직원을 위한 호텔 레스토랑 특별 할인',
    discountText: '15% 할인',
    location: '인터컨티넨탈 서울 코엑스',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    imageUrl: '',
    isActive: true,
    usageMethod: '예약 시 입주사 인증 후 할인 적용',
    notes: '사전 예약 필수. 주말/공휴일 제외.',
  },
  {
    id: '3',
    title: '현대백화점 COEX점 VIP 입장 혜택',
    brandName: '현대백화점 무역센터점',
    category: 'shopping',
    description: '입주사 직원 전용 VIP 라운지 및 할인 혜택',
    discountText: '5% 추가 할인',
    location: '현대백화점 무역센터점',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    imageUrl: '',
    isActive: true,
    usageMethod: '고객 서비스 센터에서 입주사 증명 후 VIP 카드 발급',
    notes: '연 1회 발급 가능.',
  },
  {
    id: '4',
    title: '코엑스 전시회 입주사 초대권',
    brandName: 'COEX',
    category: 'exhibition',
    description: '진행 중인 코엑스 전시 입주사 우대 입장',
    discountText: '무료 초대',
    location: 'COEX 전시홀',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    imageUrl: '',
    isActive: true,
    usageMethod: '앱에서 초대권 쿠폰 다운로드 후 입구에서 제시',
    notes: '1인 1매 한정. 전시별 수량 제한.',
  },
  {
    id: '5',
    title: '스타벅스 COEX점 음료 할인',
    brandName: '스타벅스',
    category: 'fnb',
    description: '코엑스 내 스타벅스 전 음료 10% 할인',
    discountText: '10% 할인',
    location: '스타벅스 COEX점',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    imageUrl: '',
    isActive: true,
    usageMethod: '앱 쿠폰 제시 또는 입주사 카드 제시',
    notes: '1일 2회 사용 가능.',
  },
];

export const mockCoupons: Coupon[] = [
  {
    id: 'c1',
    title: '코엑스몰 F&B 10% 할인 쿠폰',
    benefitId: '1',
    brandName: '코엑스몰 식당가',
    code: 'WTC-FNB-2024-001',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    status: 'available',
    downloadedAt: '2026-04-10',
  },
  {
    id: 'c2',
    title: '스타벅스 10% 할인 쿠폰',
    benefitId: '5',
    brandName: '스타벅스',
    code: 'WTC-SBX-2024-002',
    startDate: '2026-04-01',
    endDate: '2026-04-30',
    status: 'expired',
    downloadedAt: '2026-04-01',
  },
];

export const mockCoexEvents: CoexEvent[] = [
  {
    id: 'e1',
    title: '2026 서울 국제 도서전',
    startDate: '2026-04-20',
    endDate: '2026-04-28',
    location: 'COEX A홀',
    category: '도서/문화',
    imageUrl: '',
    description: '국내외 출판사 600여 개사가 참가하는 국제 도서 전시회',
    officialUrl: 'https://www.coex.co.kr',
    isActive: true,
    hasTenantDiscount: true,
  },
  {
    id: 'e2',
    title: '2026 스마트팩토리·자동화산업전',
    startDate: '2026-04-22',
    endDate: '2026-04-25',
    location: 'COEX B홀',
    category: '산업/기술',
    imageUrl: '',
    description: '스마트 제조 및 자동화 관련 최신 기술과 솔루션을 한자리에서',
    officialUrl: 'https://www.coex.co.kr',
    isActive: true,
    hasTenantDiscount: false,
  },
  {
    id: 'e3',
    title: '2026 서울 푸드테크 위크',
    startDate: '2026-05-01',
    endDate: '2026-05-04',
    location: 'COEX C홀',
    category: '식품/외식',
    imageUrl: '',
    description: '푸드테크 혁신 기업들의 솔루션과 미래 식품 트렌드 전시',
    officialUrl: 'https://www.coex.co.kr',
    isActive: true,
    hasTenantDiscount: true,
  },
  {
    id: 'e4',
    title: '2026 반려동물 박람회',
    startDate: '2026-05-10',
    endDate: '2026-05-12',
    location: 'COEX D홀',
    category: '반려동물',
    imageUrl: '',
    description: '국내 최대 규모 반려동물 전시회',
    officialUrl: 'https://www.coex.co.kr',
    isActive: true,
    hasTenantDiscount: false,
  },
];

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: 'p1',
    userId: 'u1',
    authorName: '김채용',
    companyName: '(주)테크스타트',
    category: 'recruitment',
    title: '[채용] 프론트엔드 개발자 모집합니다',
    content: '저희 회사에서 React/TypeScript 기반 프론트엔드 개발자를 모집합니다. 경력 2년 이상, 입주사 직원 우대합니다.',
    status: 'published',
    viewCount: 142,
    commentCount: 8,
    contact: '010-2345-6789',
    email: 'hr@techstart.co.kr',
    createdAt: '2026-04-23',
  },
  {
    id: 'p2',
    userId: 'u2',
    authorName: '이나눔',
    companyName: '(주)글로벌컨설팅',
    category: 'secondhand',
    title: '[무료나눔] 사무용 의자 5개 드립니다',
    content: '사무실 이전으로 인해 사무용 의자 5개를 무료로 드립니다. 상태 양호. 직접 가져가실 분 연락주세요.',
    status: 'published',
    viewCount: 89,
    commentCount: 12,
    contact: '010-3456-7890',
    createdAt: '2026-04-22',
  },
  {
    id: 'p3',
    userId: 'u3',
    authorName: '박행사',
    companyName: '(주)이벤트플러스',
    category: 'event',
    title: '[세미나] AI 트렌드 2026 세미나 개최 안내',
    content: '5월 15일 오후 2시, WTC 지하 회의실에서 AI 트렌드 2026 세미나를 개최합니다. 입주사 직원 무료 참가.',
    status: 'published',
    viewCount: 203,
    commentCount: 15,
    link: 'https://event.example.com',
    createdAt: '2026-04-21',
  },
];

export const mockParkingInfo: ParkingInfo = {
  parkingName: 'WTC SEOUL 주차장',
  status: 'busy',
  updatedAt: '2026-04-24T09:30:00',
};

export const mockContacts: ContactDept[] = [
  { id: 'd1', name: '대표 고객센터', phone: '02-6000-0114', icon: 'headset' },
  { id: 'd2', name: '시설 문의', phone: '02-6000-1111', icon: 'build' },
  { id: 'd3', name: '주차 문의', phone: '02-6000-2222', icon: 'local-parking' },
  { id: 'd4', name: '냉난방 문의', phone: '02-6000-3333', icon: 'ac-unit' },
  { id: 'd5', name: '방문자 신청 문의', phone: '02-6000-4444', icon: 'person-add' },
  { id: 'd6', name: '공사/작업 문의', phone: '02-6000-5555', icon: 'construction' },
  { id: 'd7', name: '분실물 문의', phone: '02-6000-6666', icon: 'search' },
];

export const mockPolls: Poll[] = [
  {
    id: 'poll1',
    title: 'GITC 공사 관련 불편사항 조사',
    description:
      '현재 진행 중인 GITC 공사로 인한 불편사항을 파악하여 개선 대책을 마련하고자 합니다. 솔직한 의견을 부탁드립니다.',
    category: '시설/공사',
    startDate: '2026-04-20',
    endDate: '2026-05-10',
    isAnonymous: true,
    allowMultiple: false,
    showResults: true,
    totalParticipants: 87,
    status: 'ongoing',
    createdAt: '2026-04-20',
    questions: [
      {
        id: 'q1',
        text: '공사로 인해 가장 불편한 점은 무엇인가요?',
        type: 'single',
        required: true,
        options: [
          { id: 'o1', text: '소음 문제', voteCount: 32 },
          { id: 'o2', text: '통행 동선 변경', voteCount: 28 },
          { id: 'o3', text: '주차 공간 감소', voteCount: 18 },
          { id: 'o4', text: '먼지/분진 발생', voteCount: 9 },
        ],
      },
      {
        id: 'q2',
        text: '공사 관련 불편 사항을 주로 언제 겪으시나요? (복수 선택 가능)',
        type: 'multiple',
        required: true,
        options: [
          { id: 'o5', text: '출근 시간대 (오전 8~10시)', voteCount: 41 },
          { id: 'o6', text: '점심 시간대 (오전 12~14시)', voteCount: 25 },
          { id: 'o7', text: '퇴근 시간대 (오후 17~19시)', voteCount: 38 },
          { id: 'o8', text: '종일 불편함', voteCount: 15 },
        ],
      },
      {
        id: 'q3',
        text: '현재 공사 관련 공지 및 안내가 충분하다고 생각하시나요?',
        type: 'rating',
        required: true,
      },
      {
        id: 'q4',
        text: '추가로 개선되었으면 하는 사항이 있으시면 자유롭게 작성해 주세요.',
        type: 'text',
        required: false,
      },
    ],
  },
  {
    id: 'poll2',
    title: 'WTC 멤버십 혜택 선호도 조사',
    description:
      '입주사 직원분들이 가장 원하는 멤버십 혜택이 무엇인지 파악하여 혜택을 강화하고자 합니다.',
    category: '멤버십',
    startDate: '2026-04-15',
    endDate: '2026-04-30',
    isAnonymous: false,
    allowMultiple: false,
    showResults: true,
    totalParticipants: 142,
    status: 'ongoing',
    createdAt: '2026-04-15',
    questions: [
      {
        id: 'q1',
        text: '현재 WTC 멤버십 혜택에 얼마나 만족하시나요?',
        type: 'score',
        required: true,
        minScore: 1,
        maxScore: 5,
      },
      {
        id: 'q2',
        text: '가장 자주 이용하는 혜택 카테고리는 무엇인가요?',
        type: 'single',
        required: true,
        options: [
          { id: 'o1', text: 'F&B (식음료) 할인', voteCount: 58 },
          { id: 'o2', text: '쇼핑 할인', voteCount: 31 },
          { id: 'o3', text: '호텔 우대', voteCount: 24 },
          { id: 'o4', text: '코엑스 전시/문화', voteCount: 29 },
        ],
      },
      {
        id: 'q3',
        text: '앞으로 추가되었으면 하는 혜택을 선택해 주세요. (복수 선택 가능)',
        type: 'multiple',
        required: true,
        options: [
          { id: 'o5', text: '헬스장/피트니스 할인', voteCount: 73 },
          { id: 'o6', text: '세탁/케어 서비스 할인', voteCount: 44 },
          { id: 'o7', text: '병원/의원 우대', voteCount: 56 },
          { id: 'o8', text: '편의시설 (세차, 세탁) 할인', voteCount: 38 },
          { id: 'o9', text: '온라인 쇼핑 제휴 할인', voteCount: 61 },
        ],
      },
    ],
  },
  {
    id: 'poll3',
    title: 'WTC Membership 앱 기능 만족도 조사',
    description: '앱을 사용해 보신 소감을 알려주세요. 여러분의 의견이 앱을 더 좋게 만듭니다.',
    category: '앱 서비스',
    startDate: '2026-04-24',
    endDate: '2026-05-24',
    isAnonymous: true,
    allowMultiple: false,
    showResults: false,
    totalParticipants: 23,
    status: 'ongoing',
    createdAt: '2026-04-24',
    questions: [
      {
        id: 'q1',
        text: '전반적인 앱 사용 경험은 어떠셨나요?',
        type: 'rating',
        required: true,
      },
      {
        id: 'q2',
        text: '가장 유용한 기능은 무엇인가요?',
        type: 'single',
        required: true,
        options: [
          { id: 'o1', text: '공지사항 확인', voteCount: 8 },
          { id: 'o2', text: '멤버십 혜택 조회', voteCount: 7 },
          { id: 'o3', text: '신청 메뉴', voteCount: 4 },
          { id: 'o4', text: '코엑스 전시 일정', voteCount: 4 },
        ],
      },
      {
        id: 'q3',
        text: '개선이 필요한 점이나 추가하고 싶은 기능을 알려주세요.',
        type: 'text',
        required: false,
      },
    ],
  },
  {
    id: 'poll4',
    title: '주차 이용 만족도 조사',
    description: '코엑스 행사 기간 주차 이용에 관한 만족도를 조사합니다.',
    category: '시설/주차',
    startDate: '2026-04-01',
    endDate: '2026-04-20',
    isAnonymous: true,
    allowMultiple: false,
    showResults: true,
    totalParticipants: 210,
    status: 'ended',
    createdAt: '2026-04-01',
    questions: [
      {
        id: 'q1',
        text: '주차 이용 전반적인 만족도는?',
        type: 'score',
        required: true,
        minScore: 1,
        maxScore: 5,
      },
      {
        id: 'q2',
        text: '주차 혼잡 시 가장 불편한 점은?',
        type: 'single',
        required: true,
        options: [
          { id: 'o1', text: '입차 대기 시간 과다', voteCount: 89 },
          { id: 'o2', text: '자리 찾기 어려움', voteCount: 67 },
          { id: 'o3', text: '안내 표지 부족', voteCount: 35 },
          { id: 'o4', text: '출차 시간 지연', voteCount: 19 },
        ],
      },
    ],
  },
];
